import type { Metadata } from 'next'
import './globals.css'
import SessionWrapper from './components/SessionWrapper'
import Nav from './components/Nav'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="light pt-14">
          <Providers>
            <Nav/>
            {children}
          </Providers>
        </body>
      </html>
    </SessionWrapper>
  )
}
